{
 "title": "Go Runtime",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutine_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memory_used_bytes", "legendFormat": "{{go_memory_type}}" }
   ]
  },
  {
   "title": "Heap allocated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memory_allocated_bytes_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Goal",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memory_gc_goal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GOMAXPROCS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_processor_limit{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_goroutine_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC goal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memory_gc_goal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocated_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(go_memory_allocations_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}