{
 "title": "Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg by(instance)(\n    rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n1 -\nnode_memory_MemAvailable_bytes\n/\nnode_memory_MemTotal_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free SSD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{\n    fstype!=\"tmpfs\",mountpoint=\"/\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\navg(\n    rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n(\n1 -\nnode_memory_MemAvailable_bytes\n/\nnode_memory_MemTotal_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Free SSD",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{\n    mountpoint=\"/\",\n    fstype!=\"tmpfs\"\n}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{sensor}}" },
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{type}}" }
   ]
  }
 ]
}