{
 "title": "Container",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name)(\n    rate(\n        container_cpu_usage_seconds_total[$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "filesystem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "container_fs_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(\n    container_network_receive_bytes_total[$__rate_interval]\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(\n    container_network_transmit_bytes_total[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}