{
 "title": "Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg by(instance)(\n    rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n1 -\nnode_memory_MemAvailable_bytes\n/\nnode_memory_MemTotal_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free SSD",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{\n    fstype!=\"tmpfs\",mountpoint=\"/\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  }
 ]
}