{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "operation",
    "query": {
     "query": "label_values(app_operation_runs_total,$operation)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# VM Train Automation Overview" } },
  {
   "title": "Training Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    app_operation_runs_total{\n      operation=\"training\"\n    }[$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tactics runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    app_operation_runs_total{\n      operation=\"tactics\"\n    }[$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    app_operation_failed_total[$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    http_server_request_duration_seconds_count[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(operation)(\n    rate(app_operation_duration_sum[$__rate_interval])\n)\n/\nsum by(operation)(\n    rate(app_operation_duration_count[$__rate_interval])\n)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le)(\n    rate(\n      http_server_request_duration_seconds_bucket[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(http_request_method)(\n    rate(\n        http_server_request_duration_seconds_count[$__rate_interval]\n    )\n)",
     "legendFormat": "{{http_request_method}}"
    }
   ]
  }
 ]
}